import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
function NavBar(){
  return (
    <nav className="flex w-full items-center justify-between p-5 font-semibold border-b">
        <div className="text-3xl">Credit</div>
        <div className="text-3xl">Sign In</div>
    </nav>
  )
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <NavBar/>

        {children}
        
      </body>
    </html>
  );
}
